language: php

php:
    - 7.3
    - 7.4
    - 8.0
    - nightly

env:
    global:
        # GH_TOKEN define in repository settings on travis-ci.com
        - GH_REPO: github.com/locomotivemtl/charcoal-contrib-communicator.git
        - GH_PAGES: locomotivemtl.github.io/charcoal-contrib-communicator

matrix:
    allow_failures:
        - php: 8.1
        - php: nightly

before_install:
    - composer self-update --quiet

install:
    - composer install --no-interaction --no-suggest
    - mkdir -p build/logs/

script:
    - composer phplint
    - composer phpcs
    # - composer phpunit -- --coverage-clover "build/logs/clover.xml"

after_script:
    - php vendor/bin/php-coveralls -v

notifications:
    slack: locomotivemtl:d9h8ZWwTZ6b3WUsSP9s26nb1
    email: charcoal@locomotive.ca
